### ISSUE TITLE
Block importing of CIViC Does not support terms that don't have matching Relevance term

### ISSUE THREAD

**Issue by cgrisdale** [bcgsc/pori_graphkb_loader#25]
Currently we support importing CIViC 'Predictive - Does not support - Sensitivity' statements. The code change required to load these statements has caused unintentional loading of other evidence types with evidence direction = Does not support and mapping them to the same Relevance terms as those with evidence direction = Supports.
Examples:
Functional - Does not support - Neomorphic
Prognostic - Does not support - Better outcome

**Comment by creisle** [comment]
It would be good to start with adding these cases into the tests and seeing why the function isn't throwing an error (or why the error isn't propagating if it does)

The other important thing here will probably be adding functionality to keep a list of entries from CIvic we should be deleting in GraphKB. I'll make a separate ticket for that since it will be a bit more complicated

Do you know how many entries were imported this way?
